### ISSUE TITLE
analyzer: reindex bag files if needed

### ISSUE THREAD

**Issue by floweisshardt** [floweisshardt/atf#103]
sometimes tests are aborted (e.g. due to time limit), this results in unindexed bag files altought there is (partially) usefull data recorded. The analyzer skips this bag files and adds `no result` to all the testblocks, athough some testblocks finished successfully.

if reindexing the bag file and the running the analyzer will result in successfull testblocks and partially executed testblocks, see
```
    name: "ts0_c1_r0_e0_s0_0"
    robot: "diff"
    env: "office"
    test_config: "dwa_local_planner"
    testblockset: "testblockset1"
    groundtruth_result: False
    groundtruth_error_message: "\n   - testblock 'testblock_rooms': \n     - metric 'tf_length_translation': no result\n\
  \     - metric 'tf_length_rotation': no result\n     - metric 'time': no result\n\
  \   - testblock 'testblock_all': \n     - metric 'tf_length_translation': no result\n\
  \     - metric 'interface': no result\n     - metric 'tf_length_rotation': no result\n\
  \     - metric 'time': no result"
    results: 
      - 
        name: "testblock_rooms"
        groundtruth_result: False
        groundtruth_error_message: "\n     - metric 'tf_length_translation': no result\n     - metric 'tf_length_rotation':\
  \ no result\n     - metric 'time': no result"
        results: 
          - 
            name: "tf_length_translation"
            started: True
            finished: False
            data: None
            groundtruth_result: False
            groundtruth_error_message: "no result"
            groundtruth: 50
            groundtruth_epsilon: 49
            details: []
          - 
            name: "tf_length_rotation"
            started: True
            finished: False
            data: None
            groundtruth_result: False
            groundtruth_error_message: "no result"
            groundtruth: 50
            groundtruth_epsilon: 49
            details: []
```
For the partially executed testblocks it's ok to have `data: None` but the error message should be `no result (did not finish testblock)` to indicate.
