### ISSUE TITLE
install: merging travis.rosinstall does not clone atf sources

### ISSUE THREAD

**Issue by gavanderhoorn** [floweisshardt/atf#35]
The [installation](https://github.com/ipa-fmw/atf/blob/docu/doc/Installation.md) instructions under the step labeled _Get ATF sources from github_ instruct to `wstool merge https://raw.githubusercontent.com/ipa-fmw/atf/master/.travis.rosinstall` into a catkin workspace to get the sources.

The referenced file only contains a stanza for `ros_comm`, which seems to not have any relation to this project:

``` yaml
- git:
    uri: 'https://github.com/ros/ros_comm.git'
    local-name: ros_comm
    version: indigo-devel
```

I just `git clone`d the repository to my workspace, which seems to work as well.
